name:                 HASKy
version:              0.1.0.0
visibility:           public
id:                   HASKy-0.1.0.0-inplace
key:                  HASKy-0.1.0.0-inplace
license:              MIT
maintainer:           oleksii.sokoliuk@mao.kiev.ua
author:               Oleksii Sokoliuk
category:             Physics 
abi:                  inplace
exposed:              True
exposed-modules:      Cosmology HMF Helper IGM Lookup Pk SMF StarFormation
import-dirs:
    /home/oleksii/HASKy/dist-newstyle/build/x86_64-linux/ghc-9.4.8/HASKy-0.1.0.0/build

library-dirs:
    /home/oleksii/HASKy/dist-newstyle/build/x86_64-linux/ghc-9.4.8/HASKy-0.1.0.0/build

library-dirs-static:
    /home/oleksii/HASKy/dist-newstyle/build/x86_64-linux/ghc-9.4.8/HASKy-0.1.0.0/build

dynamic-library-dirs:
    /home/oleksii/HASKy/dist-newstyle/build/x86_64-linux/ghc-9.4.8/HASKy-0.1.0.0/build

data-dir:             /home/oleksii/HASKy/.
hs-libraries:         HSHASKy-0.1.0.0-inplace
depends:
    GaussQuadIntegration-0.1-d9751b1b7c3f9370bdaa177be6a6bf1f3a029c35afeed6a96549cc61db93c070
    base-4.17.2.1 containers-0.6.7 directory-1.3.7.1
    lens-5.3.4-6973da031fa7f1097eae8c3c1e591738173eb06332c414f4367973e7d251145e
    mtl-2.2.2
    numeric-tools-0.2.0.1-3ff0310f4d0f73b923cefdece33bf5368de41e31937f4c9b7420515cccb01691
    parallel-3.2.2.0-ee8db206c2ec1be5ac289fec51aca365020deea63d729e9ee44709e89e6785c0
    safe-0.3.21-3853a6ce3a326d42c578f7c9f3c75fd83050ed7b2aafdece4afb5a05a5f674d0
    text-2.0.2
    vector-0.13.2.0-ffda39daee4a589508008dba3f360d80c18bddeceec85222025d708a87ab70eb

haddock-interfaces:
    /home/oleksii/HASKy/dist-newstyle/build/x86_64-linux/ghc-9.4.8/HASKy-0.1.0.0/doc/html/HASKy/HASKy.haddock

haddock-html:
    /home/oleksii/HASKy/dist-newstyle/build/x86_64-linux/ghc-9.4.8/HASKy-0.1.0.0/doc/html/HASKy
