name:                 HASKy
version:              0.1.0.0
visibility:           public
id:                   HASKy-0.1.0.0-inplace
key:                  HASKy-0.1.0.0-inplace
license:              MIT
maintainer:           oleksii.sokoliuk@mao.kiev.ua
author:               Oleksii Sokoliuk
category:             Physics 
abi:                  inplace
exposed:              True
exposed-modules:      Cosmology HMF Helper IGM Lookup Pk SMF StarFormation
import-dirs:
    /Users/oleksii/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/opt/build

library-dirs:
    /Users/oleksii/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/opt/build

library-dirs-static:
    /Users/oleksii/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/opt/build

dynamic-library-dirs:
    /Users/oleksii/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/opt/build

data-dir:             /Users/oleksii/HASKy/.
hs-libraries:         HSHASKy-0.1.0.0-inplace
depends:
    GssQdIntgrtn-0.1-873ccd75 base-4.18.3.0 containers-0.6.7
    directory-1.3.8.5 dsp-0.2.5.2-b75ddcb8 hslggr-1.3.2.0-f21c37c6
    lns-5.3.6-b1881ce9 mtl-2.3.1 nmrc-tls-0.2.0.1-9bc30d8f
    prlll-3.3.0.0-0b0749f2 sf-0.3.21-03d0bd9e text-2.0.2
    vctr-0.13.2.0-e0f1f7da

haddock-interfaces:
    /Users/oleksii/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/opt/doc/html/HASKy/HASKy.haddock

haddock-html:
    /Users/oleksii/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/opt/doc/html/HASKy
