name:                 HASKy
version:              0.1.0.0
visibility:           public
id:                   HASKy-0.1.0.0-inplace
key:                  HASKy-0.1.0.0-inplace
license:              MIT
maintainer:           oleksii.sokoliuk@mao.kiev.ua
author:               Oleksii Sokoliuk
category:             Physics 
abi:                  inplace
exposed:              True
exposed-modules:      Cosmology HMF Helper IGM Lookup Pk SMF
import-dirs:
    /Users/oleksii/Documents/GitHub/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/build

library-dirs:
    /Users/oleksii/Documents/GitHub/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/build

library-dirs-static:
    /Users/oleksii/Documents/GitHub/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/build

dynamic-library-dirs:
    /Users/oleksii/Documents/GitHub/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/build

data-dir:             /Users/oleksii/Documents/GitHub/HASKy/.
hs-libraries:         HSHASKy-0.1.0.0-inplace
depends:
    GssQdIntgrtn-0.1-00e51028 base-4.18.3.0 containers-0.6.7
    directory-1.3.8.5 lns-5.3.5-0b2abc01 mtl-2.3.1
    nmrc-tls-0.2.0.1-c495e9b7 prlll-3.2.2.0-206ed93e sf-0.3.21-4ede5588
    text-2.0.2 vctr-0.13.2.0-0f97f76f

haddock-interfaces:
    /Users/oleksii/Documents/GitHub/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/doc/html/HASKy/HASKy.haddock

haddock-html:
    /Users/oleksii/Documents/GitHub/HASKy/dist-newstyle/build/aarch64-osx/ghc-9.6.7/HASKy-0.1.0.0/doc/html/HASKy
